### ISSUE TITLE
Repository is not illegal here.

### ISSUE THREAD

**Issue by SSlinky** [pedro-w/vscode-tmlanguage#13]
![image](https://user-images.githubusercontent.com/39886505/189538090-3e1fdcb3-1fbd-4b35-81e3-97882702bd33.png)

```
  foo:
    name: some.scope.lang
    begin: "(?i)([a-z][a-z0-9_]*)\\s*\\("
    end: "\\)"
    patterns:
      - include: "#baz"
      - include: "#bar"
    repository:
      ...
```

**Comment by SSlinky** [comment]
Doesn't seem to like `repository` at any level below top.

![image](https://user-images.githubusercontent.com/39886505/189538253-3489297c-f994-478a-871a-c2a39d99c897.png)

**Comment by SSlinky** [comment]
> ![image](https://user-images.githubusercontent.com/39886505/189538090-3e1fdcb3-1fbd-4b35-81e3-97882702bd33.png)
> 
> ```
>   foo:
>     name: some.scope.lang
>     begin: "(?i)([a-z][a-z0-9_]*)\\s*\\("
>     end: "\\)"
>     patterns:
>       - include: "#baz"
>       - include: "#bar"
>     repository:
>       ...
> ```

Original is incorrect. For some reason, repository is _not_ a supported key when the rule contains begin/end matches. The second comment stands. It is supported with no matches (just patterns, as above) and with a single match rule. e.g.

```
  foo:
    name: source.foo
    match: "If.*"
    captures:
      0:
        patterns:
          - include: "#bar"
    repository:
      bar:
        name: source.bar
```

![image](https://user-images.githubusercontent.com/39886505/189539625-6aa8a84e-1742-451b-bf0f-7583a8157ca4.png)

**Comment by pedro-w** [comment]
I tried this on the current development version of vscode-tmlanguage (i.e. not the one on the marketplace) which contains the fix for #12, on a file `foo.tmLanguage.yaml` containing just this:
```
  foo:
    name: source.foo
    match: "If.*"
    captures:
      0:
        patterns:
          - include: "#bar"
    repository:
      bar:
        name: source.bar

```
The result is:
![image](https://user-images.githubusercontent.com/22172519/199447463-7198f13d-07c9-42bf-8720-462e3013d60b.png)
I think this is OK? Can you point me to another file where it's not working?
Thanks!
